/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MatchRouteImport } from './routes/match'
import { Route as ModelsRouteImport } from './routes/models'
import { Route as MatchBatchIdRouteImport } from './routes/match.$batchId'
import { Route as ModelsAgentIdRouteImport } from './routes/models.$agentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchRoute = MatchRouteImport.update({
  id: '/match',
  path: '/match',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchBatchIdRoute = MatchBatchIdRouteImport.update({
  id: '/$batchId',
  path: '/$batchId',
  getParentRoute: () => MatchRoute,
} as any)
const ModelsAgentIdRoute = ModelsAgentIdRouteImport.update({
  id: '/$agentId',
  path: '/$agentId',
  getParentRoute: () => ModelsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/match': typeof MatchRouteWithChildren
  '/models': typeof ModelsRouteWithChildren
  '/match/$batchId': typeof MatchBatchIdRoute
  '/models/$agentId': typeof ModelsAgentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/match': typeof MatchRouteWithChildren
  '/models': typeof ModelsRouteWithChildren
  '/match/$batchId': typeof MatchBatchIdRoute
  '/models/$agentId': typeof ModelsAgentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/match': typeof MatchRouteWithChildren
  '/models': typeof ModelsRouteWithChildren
  '/match/$batchId': typeof MatchBatchIdRoute
  '/models/$agentId': typeof ModelsAgentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/match' | '/models' | '/match/$batchId' | '/models/$agentId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/match' | '/models' | '/match/$batchId' | '/models/$agentId'
  id:
    | '__root__'
    | '/'
    | '/match'
    | '/models'
    | '/match/$batchId'
    | '/models/$agentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MatchRoute: typeof MatchRouteWithChildren
  ModelsRoute: typeof ModelsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match': {
      id: '/match'
      path: '/match'
      fullPath: '/match'
      preLoaderRoute: typeof MatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match/$batchId': {
      id: '/match/$batchId'
      path: '/$batchId'
      fullPath: '/match/$batchId'
      preLoaderRoute: typeof MatchBatchIdRouteImport
      parentRoute: typeof MatchRoute
    }
    '/models/$agentId': {
      id: '/models/$agentId'
      path: '/$agentId'
      fullPath: '/models/$agentId'
      preLoaderRoute: typeof ModelsAgentIdRouteImport
      parentRoute: typeof ModelsRoute
    }
  }
}

interface MatchRouteChildren {
  MatchBatchIdRoute: typeof MatchBatchIdRoute
}

const MatchRouteChildren: MatchRouteChildren = {
  MatchBatchIdRoute: MatchBatchIdRoute,
}

const MatchRouteWithChildren = MatchRoute._addFileChildren(MatchRouteChildren)

interface ModelsRouteChildren {
  ModelsAgentIdRoute: typeof ModelsAgentIdRoute
}

const ModelsRouteChildren: ModelsRouteChildren = {
  ModelsAgentIdRoute: ModelsAgentIdRoute,
}

const ModelsRouteWithChildren =
  ModelsRoute._addFileChildren(ModelsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MatchRoute: MatchRouteWithChildren,
  ModelsRoute: ModelsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
